//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumingWS.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ConsumingWS.ServiceReference1.HelloWorldResponse HelloWorld(ConsumingWS.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumingWS.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ConsumingWS.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (twoparameter) of message twoparameter does not match the default value (add)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/twoparameter", ReplyAction="*")]
        ConsumingWS.ServiceReference1.twoparameter1 add(ConsumingWS.ServiceReference1.twoparameter request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/twoparameter", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumingWS.ServiceReference1.twoparameter1> addAsync(ConsumingWS.ServiceReference1.twoparameter request);
        
        // CODEGEN: Generating message contract since the wrapper name (threeparamter) of message threeparamter does not match the default value (add1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/threeparamter", ReplyAction="*")]
        ConsumingWS.ServiceReference1.threeparamter1 add1(ConsumingWS.ServiceReference1.threeparamter request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/threeparamter", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumingWS.ServiceReference1.threeparamter1> add1Async(ConsumingWS.ServiceReference1.threeparamter request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingWS.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsumingWS.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingWS.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsumingWS.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="twoparameter", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class twoparameter {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int b;
        
        public twoparameter() {
        }
        
        public twoparameter(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="twoparameterResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class twoparameter1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int twoparameterResult;
        
        public twoparameter1() {
        }
        
        public twoparameter1(int twoparameterResult) {
            this.twoparameterResult = twoparameterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="threeparamter", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class threeparamter {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int b;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int c;
        
        public threeparamter() {
        }
        
        public threeparamter(int a, int b, int c) {
            this.a = a;
            this.b = b;
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="threeparamterResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class threeparamter1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int threeparamterResult;
        
        public threeparamter1() {
        }
        
        public threeparamter1(int threeparamterResult) {
            this.threeparamterResult = threeparamterResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsumingWS.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsumingWS.ServiceReference1.WebService1Soap>, ConsumingWS.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumingWS.ServiceReference1.HelloWorldResponse ConsumingWS.ServiceReference1.WebService1Soap.HelloWorld(ConsumingWS.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsumingWS.ServiceReference1.HelloWorldRequest inValue = new ConsumingWS.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ConsumingWS.ServiceReference1.HelloWorldRequestBody();
            ConsumingWS.ServiceReference1.HelloWorldResponse retVal = ((ConsumingWS.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumingWS.ServiceReference1.HelloWorldResponse> ConsumingWS.ServiceReference1.WebService1Soap.HelloWorldAsync(ConsumingWS.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumingWS.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ConsumingWS.ServiceReference1.HelloWorldRequest inValue = new ConsumingWS.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ConsumingWS.ServiceReference1.HelloWorldRequestBody();
            return ((ConsumingWS.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumingWS.ServiceReference1.twoparameter1 ConsumingWS.ServiceReference1.WebService1Soap.add(ConsumingWS.ServiceReference1.twoparameter request) {
            return base.Channel.add(request);
        }
        
        public int add(int a, int b) {
            ConsumingWS.ServiceReference1.twoparameter inValue = new ConsumingWS.ServiceReference1.twoparameter();
            inValue.a = a;
            inValue.b = b;
            ConsumingWS.ServiceReference1.twoparameter1 retVal = ((ConsumingWS.ServiceReference1.WebService1Soap)(this)).add(inValue);
            return retVal.twoparameterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumingWS.ServiceReference1.twoparameter1> ConsumingWS.ServiceReference1.WebService1Soap.addAsync(ConsumingWS.ServiceReference1.twoparameter request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumingWS.ServiceReference1.twoparameter1> addAsync(int a, int b) {
            ConsumingWS.ServiceReference1.twoparameter inValue = new ConsumingWS.ServiceReference1.twoparameter();
            inValue.a = a;
            inValue.b = b;
            return ((ConsumingWS.ServiceReference1.WebService1Soap)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumingWS.ServiceReference1.threeparamter1 ConsumingWS.ServiceReference1.WebService1Soap.add1(ConsumingWS.ServiceReference1.threeparamter request) {
            return base.Channel.add1(request);
        }
        
        public int add1(int a, int b, int c) {
            ConsumingWS.ServiceReference1.threeparamter inValue = new ConsumingWS.ServiceReference1.threeparamter();
            inValue.a = a;
            inValue.b = b;
            inValue.c = c;
            ConsumingWS.ServiceReference1.threeparamter1 retVal = ((ConsumingWS.ServiceReference1.WebService1Soap)(this)).add1(inValue);
            return retVal.threeparamterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumingWS.ServiceReference1.threeparamter1> ConsumingWS.ServiceReference1.WebService1Soap.add1Async(ConsumingWS.ServiceReference1.threeparamter request) {
            return base.Channel.add1Async(request);
        }
        
        public System.Threading.Tasks.Task<ConsumingWS.ServiceReference1.threeparamter1> add1Async(int a, int b, int c) {
            ConsumingWS.ServiceReference1.threeparamter inValue = new ConsumingWS.ServiceReference1.threeparamter();
            inValue.a = a;
            inValue.b = b;
            inValue.c = c;
            return ((ConsumingWS.ServiceReference1.WebService1Soap)(this)).add1Async(inValue);
        }
    }
}
